name: Push to Azure DevOps

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  push-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch the full history to avoid shallow clone issues

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Push to Azure DevOps
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        # Add Azure DevOps repository as a remote
        git remote add azure https://2sqp832Zf4zGXXlBltXd4K5jHlhtpc4IwceJ47bqXFvOPukrK4y0JQQJ99BAACAAAAAr66ZhAAASAZDOnjBx:x-oauth-basic@dev.azure.com/venubura123/project1/_git/DEMOREPO1
        # Push changes to Azure DevOps
        git push azure main --force

          # Commit and push changes
          git add .
          git commit -m "Sync changes from GitHub Actions"
          git push origin main
